Mixing score default thresholds
angelolab/ark-analysis pull request #1015
Opened 2023-06-14 20:10 UTC by camisowers

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

After testing the mixing score on 100 images and across various populations, we determined that total cell count was more useful to restrict rather than counts for the individual populations. As a result, we need to be more restrictive with the ratio of cells that we allow. The defaults that seem to work best are `ratio_threshold=5` and `cell_count_thresh=200`.

For plotting the ratios in the mixing notebook, we should drop any bigger than 15. Large ratio values just mess with the x axis and makes the plots hard to interpret. 
![Image](https://user-images.githubusercontent.com/38049893/243806896-241d6cf3-5a52-44f0-b741-e57738ad3416.png)

![Image](https://user-images.githubusercontent.com/38049893/243807438-018af721-bde7-400f-8d2b-b2b8d1ac0aae.png)

**How did you implement your changes**

Change the threshold default values in both the notebook and the code. For the output file, only return one `cell_ratio` value per image, instead of both the pop1/pop2 ratio and pop2/pop1 ratio.

Adjust the notebook to 
1. Check for and automatically generate the specified neighbor matrix, rather than rely on the user to run the correct cell. 
2. Tweak the ratio plots to have x-limit 15 and the mixing histogram plot to always start at 0.

**Remaining issues**

N/A

2023-06-14 22:52 UTC, srivarra requested changes
Looking goood, just a `np.nan` filtering suggestion.

2023-06-14 22:52 UTC, srivarra commented on src/ark/analysis/neighborhood_analysis.py
> +    targ_ref_remove_nan = [x for x in targ_ref_ratio if x < 15 and str(x) != 'nan']
```python
targ_ref_ratio = np.array(targ_ref_ratio)
targ_ref_remove_nan= targ_ref_ratio[~np.isnan(targ_ref_ratio)]
```

I'd recommend using casting these two lists to numpy arrays and then using the builtin `np.isnan` function to filter out all `np.nan` values.

2023-06-15 18:54 UTC, srivarra approved these changes

2023-06-15 20:13 UTC, ngreenwald approved these changes
Nice stuff

2023-06-15 20:14 UTC, merged