Optional normalization for generic_cell_clustering.ipynb
angelolab/ark-analysis pull request #1027
Opened 2023-07-25 19:50 UTC by camisowers

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**
Closes #1000. Make the 99.9 percentile normalization in cell clustering optional.

**How did you implement your changes**
Adds a `normalize` flag to `train_cell_SOM` and in the CellSOMCluster class which is defaulted to True.
Changing this arg to False will not conduct 99.9 percentile normalization on the data before cell clustering.

**Remaining issues**
N/A

2023-07-25 21:49 UTC, alex-l-kong requested changes
One comment about notebook documentatio

2023-07-25 21:49 UTC, alex-l-kong commented on templates/generic_cell_clustering.ipynb
>  {
<p>It's better to allow the user to set <code>normalize</code> in section 1. Either put it in its own cell or add it to one of the other param setting cells.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/angelolab/ark-analysis/pull/1027/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='17'/>

2023-07-26 17:04 UTC, srivarra approved these changes

2023-07-26 22:20 UTC, alex-l-kong approved these changes

2023-07-29 00:55 UTC, cliu72 commented on templates/generic_cell_clustering.ipynb
>  {
<p>I think just a small typo - <code>cell_som_cluster_cols</code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/angelolab/ark-analysis/pull/1027/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2023-07-29 00:56 UTC, cliu72 reviewed
Looks good to me, just one small typo in the jupyter notebook

2023-08-01 01:20 UTC, cliu72 approved these changes

2023-08-02 09:02 UTC, JLrumberger commented on templates/generic_cell_clustering.ipynb
> +    "Whether to normalize each of the `cell_som_cluster_cols` by their 99.9% value prior to training the data. Set to `False` to skip this normalization step."
Text could be changed from "training the data" to "training the SOM".

2023-08-02 20:21 UTC, merged