Update progress bars
angelolab/ark-analysis pull request #1031
Opened 2023-07-31 22:18 UTC by camisowers

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #1028. Add current processing FOV name to progress bar output in the ark notebooks.

**How did you implement your changes**

Update the FOV name at start of each code block.

**Remaining issues**

N/A

2023-08-01 21:52 UTC, srivarra requested changes
Looks great, just a `tqdm` import suggestion and some units are missing in a few loops

2023-08-01 21:52 UTC, srivarra commented on src/ark/segmentation/fiber_segmentation.py
> +from tqdm.notebook import tqdm
we should use `from tqdm.auto import tqdm` so `tqdm` can decide where it's running.

2023-08-01 21:52 UTC, srivarra commented on src/ark/analysis/neighborhood_analysis.py
>      with tqdm(total=len(included_fovs), desc="Neighbors Matrix Generation") \
`unit` here

2023-08-01 21:52 UTC, srivarra commented on src/ark/analysis/spatial_analysis_utils.py
>      with tqdm(total=len(fov_files), desc="Distance Matrix Generation") as dist_mat_progress:
`unit` here

2023-08-01 21:52 UTC, srivarra commented on src/ark/analysis/spatial_enrichment.py
>      with tqdm(total=len(all_label_fovs), desc="Channel Spatial Enrichment") as chan_progress:
`unit` here

2023-08-01 21:52 UTC, srivarra commented on src/ark/segmentation/fiber_segmentation.py
> +    with tqdm(total=len(fovs), desc="Fiber Segmentation") as fibseg_progress:
`unit` here

2023-08-01 21:52 UTC, srivarra commented on src/ark/utils/data_utils.py
>          for fov in fovs:
`unit` here.

2023-08-01 21:52 UTC, srivarra commented on src/ark/utils/data_utils.py
> +            neigh_mask_progress.set_postfix(FOV=fov)
`unit`  here.

2023-08-01 22:38 UTC, alex-l-kong reviewed
Nothing to add on top of Sri's comments.

2023-08-01 22:38 UTC, srivarra approved these changes
Looks good!

2023-08-01 23:28 UTC, alex-l-kong approved these changes

2023-08-09 18:23 UTC, HPiyadasa commented
Looks great

2023-08-09 18:26 UTC, HPiyadasa approved these changes

2023-08-09 18:45 UTC, merged