Allow user to dynamically set batch size of pixel SOM assignments
angelolab/ark-analysis pull request #1069
Opened 2023-09-28 23:04 UTC by alex-l-kong

**What is the purpose of this PR?**

The current hard-coded batch size of 100 makes pixel SOM cluster assignment extremely slow. For a powerful machine (and even modern-day M1's and M2's), it can handle a much larger batch size and offer a 100x+ speedup.

**How did you implement your changes**

Pass an argument through the PixelSOMCluster process called `num_parallel_pixels`, which controls how many SOM clusters get assigned at once.

2023-10-13 00:59 UTC, cliu72 commented on src/ark/phenotyping/cluster_helpers.py
>          # work in batches of 100 to account to support large dataframe sizes
A verrrrry small comment - but it'd be good to update this comment here so it doesn't say "batches of 100"

2023-10-13 01:05 UTC, cliu72 requested changes
Sorry for the late review! Just some small requests.

2023-10-23 21:15 UTC, cliu72 requested changes
Can we add the same functionality to `assign_som_clusters` in the `CellSOMCluster` class in cluster_helpers.py (and cell_som_clustering.py respectively)?

2023-10-25 22:17 UTC, alex-l-kong commented
> Can we add the same functionality to `assign_som_clusters` in the `CellSOMCluster` class in cluster_helpers.py (and cell_som_clustering.py respectively)?

Sure, same batch size work?

2023-10-25 22:58 UTC, cliu72 commented
> > Can we add the same functionality to `assign_som_clusters` in the `CellSOMCluster` class in cluster_helpers.py (and cell_som_clustering.py respectively)?
> 
> Sure, same batch size work?

Yup, that works.

2023-10-27 00:58 UTC, cliu72 approved these changes
Looks good!

2023-10-30 19:54 UTC, merged