Removed Docker Builds
angelolab/ark-analysis pull request #1168
Opened 2024-10-11 17:06 UTC by srivarra

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Docker is no longer necessary for Ark Analysis. Windows users can now completely use Ark Analysis without Docker or on WSL.

**How did you implement your changes**

This PR removes the `Dockerfile` and docker workflows from the repository, along with documentation for how to use Ark with Docker.
**Remaining issues**

N/A

2024-10-14 19:20 UTC, camisowers approved these changes
Looks great! One minor suggestion.

2024-10-14 19:20 UTC, camisowers commented on docs/_rtd/faq.md
> -
We could probably point out that this is likely an issue with the ark_env and to ensure ark_env is activated before opening jupyter, or to try re-installing.

2024-10-15 20:32 UTC, alex-l-kong requested changes
One additional section that could be removed.

2024-10-15 21:22 UTC, srivarra commented on docs/_rtd/windows_setup.md
> +**We find it best to download and configure WSL 2 before anything else**. We recommend using the [Command Prompt](https://en.wikipedia.org/wiki/Cmd.exe) to run these commands (and later ones). You ca
Yeah I think this is reasonable, if anyone wants to run it on WSL2 they probably already have the know how to set it up themselves.

2024-10-17 22:45 UTC, alex-l-kong approved these changes
👍

2024-10-17 23:01 UTC, merged