logging
angelolab/ark-analysis pull request #288
Opened 2020-10-23 21:30 UTC by omerbt

**What is the purpose of this PR?**

To add logging for `deepcell_service_utils` to describe the current stage of the pipeline. closes #283 

**How did you implement your changes**

Added logging when: creating the zip file, calling kiosk-client, and extracting the tif files from the output of deepcell. 

**Remaining issues**

kiosk-client writes its own logs (using Python `logging` module). Maybe it is worth thinking if/how to integrate with it so we can show these logs in the pipeline (for example, currently there will be no indication in our pipeline if there was a problem when uploading the files to deepcell server).

2020-10-23 23:12 UTC, ngreenwald requested changes
That's a good point about passing errors from the deepcell server. I've written a test so that it will fail if you provide images of the wrong shape. Can you try sending an image that's the wrong shape (i.e. 512x512x4 or something) to the server and see what that looks like in the jupyter notebook? If it shows up then we should be fine, but if it doesn't then we might need to investigate what the best way is to propagate that error message to the notebook.

2020-10-24 13:54 UTC, omerbt commented
We get a UserWarning (that is generated in `create_deepcell_output`) saying that the tif file was not found for that fov.
('Deep Cell output file was not found for {fov}.' )

2020-10-24 16:06 UTC, ngreenwald requested changes
Can you ask Will if there's a way for us to display the ValueError that is getting raised on the server?

That's what is preventing the FOV from being generated in the first place, so it would be nice if we could just show whatever internal error is being raised by the kiosk.

2020-10-24 17:23 UTC, ngreenwald approved these changes

2020-10-24 17:39 UTC, merged