Add documentation for FAQ
angelolab/ark-analysis pull request #308
Opened 2020-10-28 18:03 UTC by alex-l-kong

**What is the purpose of this PR?**

We've received a lot of questions over the past few weeks that can be easily answered. To avoid unnecessary back-and-forth, we put some commonly-asked questions in a specific FAQ page in our documentation.

**How did you implement your changes**

We add a file called `faq.md` in our `docs/_rtd` folder.

**Remaining issues**

I've started off with 4 fairly basic questions. Any more we need to address?

2020-10-28 20:34 UTC, ngreenwald requested changes
Great, can you add a link in the ReadMe directing them here, and also edit the Bug/question issue template with a link asking them to check the FAQ first

2020-10-28 23:11 UTC, ngreenwald commented
I removed the last two FAQ items you added; I think we might eventually have issues with people deleting files, but until they do, giving them information about git commands will only lead to problems. 

I also updated the question template as well. Let me know what you think

2020-10-28 23:42 UTC, alex-l-kong commented
@ngreenwald looks great!

2020-10-29 04:08 UTC, ngreenwald approved these changes

2020-10-29 04:52 UTC, merged