Add SOM implementation
angelolab/ark-analysis pull request #374
Opened 2021-01-18 20:55 UTC by alex-l-kong

**What is the purpose of this PR?**

Add SOM implementation. A redo of the previous branch which got completely messed up.

2022-02-26 03:04 UTC, ngreenwald requested changes
Looking nice! There's some random files that look like they got added in here too:
`data/example_dataset/flowsom_data/deepcell_output`, and 'flowsom_data/input_data`. Are those here for a particular reason?

2022-02-26 03:04 UTC, ngreenwald commented on ark/utils/notebooks_test.py
> +        # TODO: see what Brian discovers about R testing, then add cell clustering tests
How long does the pixel clustering tests take? Can we add a simple cell clustering one to make sure the notebook runs?

2022-03-08 23:58 UTC, alex-l-kong commented
The notebook tests now run the visualization code, mocking only the necessary files and directories needed.

2022-03-09 16:52 UTC, ngreenwald requested changes
Looks good, but some commented code still in here

2022-03-09 16:52 UTC, ngreenwald commented on ark/utils/notebooks_test.py
> +# def test_segment_image_data():
Comments

2022-03-09 19:35 UTC, ngreenwald commented
Awesome, looks good. Will you make a new release and bump to v0.3.0

2022-03-09 19:35 UTC, merged