Create GoogleDrivePath Usage Documentation
angelolab/ark-analysis pull request #440
Opened 2021-08-03 23:44 UTC by ackagel

Instead of an example notebook, a full documentation page on using the `GoogleDrivePath` API is added. 

This mitigates the confusion users would have trying to run the example notebook, and lets them gradually familiarize themselves with `GoogleDrivePath` usage as they need it.

2021-08-04 20:43 UTC, alex-l-kong requested changes
Looks good, just a few minor changes.

2021-08-04 20:43 UTC, alex-l-kong commented on docs/_rtd/google_drive_usage.md
> +locally since it's very small relative to the size of the dataset.  On the other hand, we'll
```suggestion
locally since it's very small relative to the size of the dataset.  On the other hand, we
```

2021-08-04 20:43 UTC, alex-l-kong commented on docs/_rtd/google_drive_usage.md
> +(TODO: add a link here...).
https://github.com/angelolab/ark-analysis/issues

2021-08-04 20:43 UTC, alex-l-kong commented on docs/_rtd/google_drive_usage.md
> +```
This part shouldn't be necessary.

2021-08-05 19:58 UTC, bcollica reviewed
This is great, I think it's much more intuitive presented this way.

2021-08-05 19:58 UTC, bcollica commented on docs/_rtd/google_drive_usage.md
> +Image data can be very large, and it can be difficult to keep all of it on you local hard drive.
```suggestion
Image data can be very large, and it can be difficult to keep all of it on your local hard drive.
```

2021-08-05 22:07 UTC, ngreenwald requested changes
Overall looks great

2021-08-05 23:03 UTC, ackagel commented on docs/_rtd/google_drive_usage.md
> +google_drive_utils.init_google_drive_api("passcode")
They would replace the `"passcode"` string with the actual passcode yep.  I can clarify that if need be.

Also, now that I think about it, I should add some details for signing in to their google drive account after running that code cell.

2021-08-05 23:06 UTC, ackagel commented on docs/_rtd/google_drive_usage.md
> +`Segment_Image_Data` notebook, `deepcell_input_dir` only stores the Mesmer-compatable formatted
Only non-negligible hinderance on performance would be in the case of poor upload **_or_** download speed.

With that being the case, maybe I just wrap this comment around an **'in the case of slow upload/download speed'** section?

2021-08-05 23:16 UTC, ngreenwald commented on docs/_rtd/google_drive_usage.md
> +`Segment_Image_Data` notebook, `deepcell_input_dir` only stores the Mesmer-compatable formatted
Yeah, move this to the bottom, and change from "this is what you should do" to "this is one way to remedy slow upload/download"

2021-08-10 22:56 UTC, alex-l-kong reviewed
Looks good to me!

2021-08-11 00:17 UTC, ngreenwald approved these changes
Looks good

2021-08-11 00:38 UTC, merged