Deploy a Docker image using Travis
angelolab/ark-analysis pull request #503
Opened 2022-02-15 19:05 UTC by alex-l-kong

**What is the purpose of this PR?**

Addresses one part of #502. Instead of having the user build the Docker locally every time, we want to push a new Docker image on a tagged commit. In this way, the user can simply download the latest Docker image.

We piggyback off https://github.com/vanvalenlab/deepcell-tf/blob/ad2b019fa912a7d417964429e4c4142abd0d3175/.travis.yml#L72.

**How did you implement your changes**

Add a new entry to the `jobs` section of `.travis.yml` called `docker_deploy` which handles pushing to Docker Hub.

**Remaining issues**

We won't be able to find potential bugs until we push an actual tagged commit. Additionally, some of the following issues may need to be resolved with a 2nd PR:

- The environment variables `$TRAVIS_REPO_SLUG` and `$TRAVIS_TAG` may need to be edited
- Add a Docker Hub badge to `README.md`
- Change documentation instructing user to download from Docker Hub and not build locally

2022-02-15 19:45 UTC, alex-l-kong commented
I'm requesting a review on this for now, but some aspects may require some more discussion, an official test on a commit to master, or additional Travis/Docker account setup.

2022-02-15 22:33 UTC, alex-l-kong commented
Per our discussion today, once this branch is ready to be merged in I'll change the `docker_deploy` job to run on `tag IS present` as opposed to `branch = master`.

2022-02-15 22:37 UTC, ngreenwald requested changes
Okay I updated the environmental variables

2022-02-16 02:14 UTC, ngreenwald requested changes

2022-02-16 02:14 UTC, ngreenwald commented on README.md
> +docker pull angelolab/ark-analysis:latest
Did you check that this works? If so looks good

2022-02-16 21:06 UTC, ngreenwald approved these changes

2022-02-16 21:06 UTC, ngreenwald commented
Looks good. Can you make a new release to trigger the push?

2022-02-16 23:21 UTC, merged