Removed mibi directory
angelolab/ark-analysis pull request #508
Opened 2022-02-24 22:26 UTC by srivarra

- deleted the mibi folder
- adjusted templates_qc notebooks

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes angelolab/toffy#20. It removes the `mibi` directory as it is now in `toffy`.

**How did you implement your changes**

A detailed description of what modifications you made to the codebase. Please include details on what functions you needed to change, how you changed them, and why. If you added new functions, give a description of what they do, as well as any specific design decisions

Removed `ark\mibi` and changed the imports in the `templates_qc` notebooks. They import from toffy directly now.

**Remaining issues**

None.

2022-02-25 22:18 UTC, ngreenwald requested changes
Looks good, just a couple commented lines that can be removed. 

It's not clear from the github overview, but you deleted the entire /mibi folder and /templates_qc folder, right, not just the files in them?

2022-02-25 22:18 UTC, ngreenwald commented on ark/utils/notebooks_test.py
> +#                                    '..', '..', 'templates_qc',
This commented stuff can be deleted as well

2022-02-25 22:25 UTC, srivarra commented
Correct.

2022-02-26 03:04 UTC, ngreenwald approved these changes

2022-02-26 03:04 UTC, merged