Added option to ignore hidden files and directories
angelolab/ark-analysis pull request #510
Opened 2022-02-28 20:38 UTC by srivarra

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #506. The purpose of this PR is to add an option for the user to ignore hidden directories in `io_utils::list_folders` and hidden files in `io_utils::list_files`.

**How did you implement your changes**

When `ignore_hidden == True`, the functions ignore all files and folders which start with a `.`. Defaults to `True`.

**Remaining issues**

None.

2022-03-01 20:01 UTC, ngreenwald requested changes
Looks good, minor comments only

2022-03-01 20:01 UTC, ngreenwald commented on ark/utils/io_utils_test.py
> +        assert sorted(get_all) == sorted([dir for dir in dirnames if not dir.startswith('.')])
and here

2022-03-01 20:50 UTC, alex-l-kong approved these changes
Nothing else to add, looks good!

2022-03-02 19:51 UTC, ngreenwald approved these changes

2022-03-02 19:51 UTC, merged