Remove intermediate `_clustered`/`_consensus` directories/files from pixel and cell clustering pipeline
angelolab/ark-analysis pull request #586
Opened 2022-06-03 21:53 UTC by alex-l-kong

**What is the purpose of this PR?**

Closes #571. There is no need to create a separate `pixel_mat_clustered` directory/`cell_mat_clustered` file as the data is just the channel expression/pixel cluster count expression values with an additional `pixel_som_cluster`/`cell_som_cluster` attached. Ditto for the `pixel_mat_consensus` directory/`cell_mat_consensus` file. These should be removed from the pixel and cell clustering processes.

**How did you implement your changes**

We should overwrite the original data with the newly created data in the `cluster_pixels`/`pixel_consensus_cluster` (and similarly for the cell clustering functions).

**Remaining issues**

There are a few extra checks we need to include for validation if the user decides to rerun the clustering pipeline in the same session.

2022-06-06 22:00 UTC, alex-l-kong commented
This branch is almost done, need to verify the outputs match up compared to the original.

2022-06-07 03:33 UTC, ngreenwald reviewed
This looks great. Did you already run both notebooks on the HIV dataset to check that everything is working?

2022-06-07 17:33 UTC, alex-l-kong commented
@ngreenwald yes, I'm currently running one more test to be sure.

2022-06-07 22:52 UTC, ngreenwald commented on templates_ark/example_cell_clustering.ipynb
>      "base_dir = \"../data/granulomaCohort_allData\"\n",
<pre class="ql-syntax" spellcheck="false">Line #6.    pixel_output_dir = 'test_candace_condense_pixel_output_dir'
</pre><p>This needs to be changed back</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/angelolab/ark-analysis/pull/586/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='5'/>

2022-06-07 22:52 UTC, ngreenwald requested changes
Looks good, just one leftover path change in the notebook

2022-06-09 21:59 UTC, ngreenwald requested changes
Looks like some merge conflicts from the normalization PR I just put in

2022-06-10 00:20 UTC, alex-l-kong commented
@ngreenwald resolved

2022-06-10 03:28 UTC, ngreenwald approved these changes

2022-06-10 03:29 UTC, merged