Place `channel_norm.feather` and `pixel_norm.feather` in the pixel directory
angelolab/ark-analysis pull request #616
Opened 2022-06-23 01:38 UTC by alex-l-kong

**What is the purpose of this PR?**

Closes #610. This PR saves the normalization files in the pixel directory for the clustering run to ensure it doesn't get overwritten. Additionally, it adds `pixel_cluster_prefix` to their names.

2022-06-24 05:06 UTC, alex-l-kong commented
@ngreenwald confirmed that the mocked function is being entered, and not passing without channel normalization on this branch.

2022-06-24 19:31 UTC, ngreenwald commented on templates_ark/example_pixel_clustering.ipynb
>      "    segmentation_dir,\n",
<p>pixel_cluster_prefix should get added here as well</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/angelolab/ark-analysis/pull/616/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='17'/>

2022-06-24 19:32 UTC, ngreenwald requested changes
looks good

2022-06-25 18:43 UTC, ngreenwald approved these changes

2022-06-25 18:43 UTC, merged