Nuclear counts loading
angelolab/ark-analysis pull request #715
Opened 2022-09-19 19:07 UTC by camisowers

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #646. 

**How did you implement your changes**

Update logic to only load nuclear image data if `nuclear_counts=True`.

2022-09-19 19:42 UTC, alex-l-kong reviewed
Just one minor code comment.

2022-09-19 19:42 UTC, alex-l-kong commented on ark/segmentation/marker_quantification.py
> +            segmentation_labels = current_labels_cell.values
The `else` clause can be condensed to something like this:

```
compartments = ['whole_cell']
segmentation_labels = current_labels_cell.values

if nuclear_counts:
    current_labels_nuc = load_utils.load_imgs_from_dir(data_dir=segmentation_dir,
                                                       files=nuclear_files,
                                                       xr_dim_name='compartments',
                                                       xr_channel_names=['nuclear'],
                                                       trim_suffix='_feature_1')
    compartments.append('nuclear')
    segmentation_labels = np.concatenate((segmentation_labels,
                                          current_labels_nuc.values)), axis=-1)
```

2022-09-20 00:57 UTC, ngreenwald requested changes
Looks good. Will you test out the segmentation notebook, deleting the `feature_1` tiffs that are generated by the deepcell call, to make sure there aren't any other hidden places where the nuclear images are assumed to exist

2022-09-20 19:27 UTC, camisowers commented
> Looks good. Will you test out the segmentation notebook, deleting the `feature_1` tiffs that are generated by the deepcell call, to make sure there aren't any other hidden places where the nuclear images are assumed to exist

The last few code sections generating and saving the cell table ran without issue!

2022-09-21 01:13 UTC, ngreenwald approved these changes
Cool, good stuff

2022-09-21 01:13 UTC, merged