Rename notebooks folder to `templates`
angelolab/ark-analysis pull request #729
Opened 2022-09-27 18:28 UTC by alex-l-kong

**What is the purpose of this PR?**

Closes #725. It's no longer necessary to suffix the `templates` folder with `_ark`; this is a remnant of when the `toffy` pipeline was here.

**How did you implement your changes**

Change any reference to `templates_ark` to `templates`.

2022-09-28 23:12 UTC, ngreenwald requested changes
Looks good. Did you use an editor/github search to make sure you got all the old template_ark references? And did you try it out yourself with the new docker script to make sure it all works?

2022-09-29 00:25 UTC, alex-l-kong commented
@ngreenwald good catch, looks like Github search isn't reliable for Jupyter notebooks. Just one minor reference fix.

`start_docker.sh` works as expected.

2022-09-29 02:46 UTC, ngreenwald commented
Sounds good. Going to wait to merge this in until we're ready for a new release to make sure people aren't stuck with an intermediate version

2022-10-03 19:00 UTC, ngreenwald approved these changes

2022-10-03 19:00 UTC, merged