Patch up `arrow` library in Docker
angelolab/ark-analysis pull request #748
Opened 2022-10-05 20:51 UTC by alex-l-kong

**What is the purpose of this PR?**

Closes #744. The `arrow` library is not installing correctly using the current Dockerfile, this will need to be patched.

**How did you implement your changes**

We'll just install `arrow` as is without pointing it to a specific repo. There doesn't exist a great binary for the `bullseye` distro we're currently using.

Additionally, package validation statements were added that test if they can be imported. These lines will terminate the `docker build` process if the package isn't found, indicating installation errors.

2022-10-05 21:18 UTC, ngreenwald requested changes
Can you give this a temporary name and switch the deployment logic to `on branch` or whatever to see if this builds correctly on dockerhub?

Maybe we can have a standardized tag for testing new images before making a release.

2022-10-06 17:44 UTC, alex-l-kong commented
> Can you give this a temporary name and switch the deployment logic to `on branch` or whatever to see if this builds correctly on dockerhub?
> 
> Maybe we can have a standardized tag for testing new images before making a release.

@ngreenwald can confirm this works with the temporary Docker image (`arrow_test`) that I pushed yesterday. There are no issues importing `arrow` anymore.

2022-10-06 20:52 UTC, ngreenwald requested changes

2022-10-06 20:52 UTC, ngreenwald commented on .travis.yml
> +      if: branch = arrow_patch
The arrow references here need to be changed back

2022-10-07 15:22 UTC, ngreenwald approved these changes

2022-10-07 15:22 UTC, merged