Example Dataset - Notebook 4
angelolab/ark-analysis pull request #763
Opened 2022-10-10 22:12 UTC by srivarra

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Addresses Part 3 of #692. Adds downloading the minimum datasets required for Notebook 4.

**How did you implement your changes**

Updates the process for Notebook 4. Updated the dataset on Hugging Face as well.

**Remaining issues**

None ATM.

2022-10-17 20:50 UTC, ngreenwald requested changes
What's different about the notebook 3 and notebook 4 datasets?

2022-10-17 21:28 UTC, srivarra commented
@ngreenwald The notebook 4 dataset contains `example_cell_output`, the data generated by notebook 3 which is needed for post clustering.

2022-10-17 22:35 UTC, srivarra commented
@ngreenwald Are you referencing the step when the metacluster labels get added to the table? If so those are saved in a separate file which is suffixed by `_cell_labels` (i.e. `cell_table_size_normalized_cell_labels.csv`)

2022-10-18 00:12 UTC, ngreenwald commented
Got it, sounds good

2022-10-18 00:36 UTC, ngreenwald requested changes
Same merge conflicts here as well

2022-10-19 18:59 UTC, ngreenwald commented on templates/4_Post_Clustering.ipynb
>      "import numpy as np\n",
<p>This cell needs to be updated. The goal is to show how to update the cell table using the threshold identified in the histogram above. This is still using ECAD</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/angelolab/ark-analysis/pull/763/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2022-10-19 19:00 UTC, ngreenwald requested changes
Looks good, just need to update the notebook comments

2022-10-19 22:23 UTC, ngreenwald commented on templates/4_Post_Clustering.ipynb
>      "import numpy as np\n",
<p>Will you add a link to this notebook (and the others) that import the example dataset with a link to the readme section, saying that there's more information there</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/angelolab/ark-analysis/pull/763/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='4'/>

2022-10-19 22:23 UTC, ngreenwald commented on templates/4_Post_Clustering.ipynb
>      "import numpy as np\n",
<p>Looks like not quite all of the changes we discussed last week got included. </p><p>The code above is identifying cells in the immune_other category which express CD3 as strongly as CD4T and CD8Ts do. These are both Tcell populations, so the cells from immune_other which have high levels of CD3 should be assigned to a new category, tcell_other. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/angelolab/ark-analysis/pull/763/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2022-10-20 20:16 UTC, ngreenwald requested changes
Notebook changes look great, looks like there's a travis issue

2022-10-20 20:17 UTC, srivarra commented
@ngreenwald Yeah, it's something on test PYPIs end it seems.

2022-10-20 20:22 UTC, ngreenwald approved these changes
Okay, the actual build is passing, I'll go ahead and merge this in. Will you run all four notebooks after clearing your cache to make sure there aren't any issues that we missed with the download logic?

2022-10-20 20:22 UTC, merged