Remove mibitiff option in notebooks
angelolab/ark-analysis pull request #772
Opened 2022-10-13 22:19 UTC by camisowers

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #686.

**How did you implement your changes**
Remove mentions of MIBItiff in the notebooks and instead use the underlying default `is_mibitiff=False` in the functions.

2022-10-13 23:57 UTC, ngreenwald requested changes
@srivarra has an open PR changing some of these same lines in the notebooks. You guys should coordinate to figure out which branch to merge where/when, resolving merge conflicts in the jupyter notebooks can be annoying sometimes.

2022-10-14 17:23 UTC, srivarra commented
@ngreenwald I'll add the changes to #736.

2022-10-14 22:41 UTC, camisowers commented
cool then we can just merge into main

2022-10-14 23:06 UTC, ngreenwald approved these changes

2022-10-14 23:06 UTC, merged