Rename `_feature_0` to `_whole_cell` and `_feature_1` to `_nuclear`
angelolab/ark-analysis pull request #786
Opened 2022-10-21 20:41 UTC by alex-l-kong

**What is the purpose of this PR?**

Closes #745. The current suffixes for the segmented images are unclear, they need to be renamed.

**How did you implement your changes**

See title.

2022-11-10 22:31 UTC, alex-l-kong commented on ark/utils/example_dataset.py
> +                                     revision="5db23d178f266fdd9bdc8db637f287eb9eb4224d")
We'll change this prior to merging into main.

2022-11-10 22:32 UTC, alex-l-kong commented on ark/utils/example_dataset_test.py
> +        revision="5db23d178f266fdd9bdc8db637f287eb9eb4224d"
Same here.

2022-11-10 23:19 UTC, ngreenwald requested changes
Changing the example dataset should have automatically uncovered any remaining references in notebooks 1-4, right?. Will you check the spatial notebooks to see if any of them have remaining references to the old format?

2022-11-11 00:10 UTC, alex-l-kong commented
> Changing the example dataset should have automatically uncovered any remaining references in notebooks 1-4, right?. Will you check the spatial notebooks to see if any of them have remaining references to the old format?

Yes, and I've verified that all the spatial notebooks are purged of old references.

2022-11-11 01:57 UTC, ngreenwald approved these changes
Looks good

2022-11-11 03:16 UTC, alex-l-kong commented
@ngreenwald can you merge this PR for me? It seems like `coveralls` is underreporting.

2022-11-11 03:18 UTC, merged