`seg_suffix` Requires Explicit File Extension
angelolab/ark-analysis pull request #848
Opened 2022-12-02 21:42 UTC by srivarra

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #842. Using file extensions other than `.tiff` for `seg_suffix` in the Notebooks: Pixel Clustering, Cell Clustering will not work due to hard-coded in extension types. It should be backwards compatible for now.

**How did you implement your changes**

`seg_suffix` used in Notebooks 2,3 will now work appropriately with `post_cluster_utils.create_mantis_project` and `plot_utils.create_mantis_dir`.

- `seg_suffix` now requires the file extension in addition to the suffix.

**Remaining issues**

N/A.

2022-12-05 23:38 UTC, ngreenwald commented
These lines are triggering a change in coveralls on different PRs. In theory we shouldn't ever be generating corrupted feather files, which is why they're variably covered. Can you either exclude them from being counted in coveralls, or generate a corrupted feather file so that the coverage is consistent? 
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/13770365/205768247-da5109c8-132e-4b94-8861-13cc4e939d88.png">

2022-12-05 23:44 UTC, ngreenwald requested changes
Looks good, see above

2022-12-06 01:10 UTC, srivarra commented
> These lines are triggering a change in coveralls on different PRs. In theory we shouldn't ever be generating corrupted feather files, which is why they're variably covered. Can you either exclude them from being counted in coveralls, or generate a corrupted feather file so that the coverage is consistent?

Got it to ignore the `(`ArrowInvalid, OSError, IOError)` lines.

2022-12-06 04:55 UTC, ngreenwald approved these changes
Looks good

2022-12-06 04:55 UTC, merged