Add `inverse` method to `ZScoreNorm` to integrate with current `matplotlib`
angelolab/ark-analysis pull request #871
Opened 2022-12-17 00:58 UTC by alex-l-kong

**What is the purpose of this PR?**

Closes #810. Pinning `matplotlib` to `3.4.2` is not a long-term solution for ensuring the colorbar scales properly.

**How did you implement your changes**

From `matplotlib==3.5.0` onwards, an `inverse` method is explicitly required in a custom `matplotlib.colors.Normalizer` derived class for it to function properly. Additionally, we should fix the min and max at -3 and 3 respectively (and not using the min and max of the input data, as Zak was doing).

To this end, we can also remove the `calibrate` method and rely on just `__call__` and `inverse`.

**Remaining issues**

We will need to make a new Docker release for this.

2022-12-20 06:49 UTC, cliu72 approved these changes
Looks good

2022-12-20 18:41 UTC, alex-l-kong commented
@ngreenwald can you please help merge this one in, a minor coveralls issue is preventing that from happening.

2022-12-20 19:42 UTC, ngreenwald requested changes
This will require a new docker as well, lets wait to discuss

2023-01-20 01:16 UTC, ngreenwald requested changes
<img width="627" alt="image" src="https://user-images.githubusercontent.com/13770365/213597215-c9e734de-8d82-4b67-8db5-d14176de2b28.png">
The new TMI requirements are not playing nicely with the matplotlib pin here I think

2023-01-20 01:21 UTC, srivarra commented
@ngreenwald Let me make a new release for TMI which'll consist of changes from angelolab/tmi#17

2023-01-20 18:30 UTC, alex-l-kong commented
@ngreenwald looks like it works now with `tmi==0.1.2`.

2023-01-20 20:41 UTC, ngreenwald approved these changes

2023-01-20 20:41 UTC, merged