Added `nuc_seg_suffix` for `filter_with_nuclear_mask`
angelolab/ark-analysis pull request #879
Opened 2023-01-10 18:56 UTC by srivarra

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #867. Allows users to supply their own custom segmentation suffixes.

**How did you implement your changes**

Added a `nuc_seg_suffix: str` parameter to `ark.phenotyping.pixel_cluster_utils.filter_with_nuclear_mask`. Updated the tests to account for this new paramteter.

**Remaining issues**

N/A.

2023-01-10 19:40 UTC, cliu72 commented on ark/phenotyping/pixel_cluster_utils.py
> +                             nuc_seg_suffix: str = "nuclear", img_sub_folder: str = None,
I think it would be better to have `nuc_seg_suffix: str="_nuclear.tiff"` here (to handle image files with different extensions).

2023-01-10 19:41 UTC, cliu72 commented on ark/phenotyping/pixel_cluster_utils.py
> +        seg_img_name: str = f"{fov}_{nuc_seg_suffix}.tiff"
Correspondingly, `seg_img_name: str = f"{fov}{nuc_seg_suffix}"` here.

2023-01-10 19:43 UTC, cliu72 requested changes
I think it'd be better to allow different file extensions for the segmentation file.

2023-01-17 01:00 UTC, cliu72 requested changes
Sorry to be neurotic about this, but can we change it slightly such that the underscore is not assumed to be in the name? 

So like the default nuc_seg_suffix has the underscore in it:
`nuc_seg_suffix: str = "_nuclear.tiff"`
And
`seg_img_name: str = f"{fov}{nuc_seg_suffix}"`

This is how it is in the existing functions that take a seg_suffix - I'm just super neurotic and would prefer it to be the same. This is what I mean by existing functions:

https://github.com/angelolab/ark-analysis/blob/e5c5ad14e4306367214e93eadefae1428a44f80c/ark/phenotyping/pixel_cluster_utils.py#L545

And in the pixel clustering notebook, seg_suffix is set as:
`seg_suffix = '_whole_cell.tiff'`

2023-01-17 17:46 UTC, srivarra commented
@cliu72 Yeah, that's no problem at all.

2023-01-18 02:14 UTC, cliu72 commented on templates/2_Pixie_Cluster_Pixels.ipynb
>      "nuclear_exclude = True\n",
<pre class="ql-syntax" spellcheck="false">Line #9.        nuc_seg_suffix="nuclear.tiff",
</pre><p>Thanks! I think this is the last change - <code>nuc_seg_suffix</code> should be <code>"_nuclear.tiff"</code> here.  </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/angelolab/ark-analysis/pull/879/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='22'/>

2023-01-23 18:40 UTC, cliu72 approved these changes
Looks good!

2023-01-23 18:42 UTC, merged