Correct 99.9% normalization to 100% normalization for "many-zero" columns
angelolab/ark-analysis pull request #894
Opened 2023-01-26 20:31 UTC by alex-l-kong

**What is the purpose of this PR?**

Closes #890. When an expression column for cell Pixie clustering is mostly zero, the 99.9% quantile value may equal 0, which will cause NaNs to appear for normalization. To prevent this, 100% quantile values should be set for those columns.

**How did you implement your changes**

Add correction in the way the normalization values are set in `CellSOMCluster.normalize_data`. Define the normalization values prior to applying them to `cell_data_sub`.

2023-02-02 02:02 UTC, cliu72 requested changes
This definitely solves the error that arises, but actually the correct behavior is for the function to ignore 0's when calculating the 99.9th percentile. For example, this is the mirroring code in `create_pixel_matrix`: https://github.com/angelolab/ark-analysis/blob/e6050fca79daeb9fb9e771f1df4e383ad54afaa6/ark/phenotyping/pixel_cluster_utils.py#L780-L782.

In that function, you are setting all 0's to nan, so the quantile function ignores those numbers. That's what we want here too.

2023-02-09 20:12 UTC, cliu72 approved these changes
Looks good

2023-02-09 20:36 UTC, alex-l-kong commented
@HPiyadasa can you please approve this if it looks good? Need it so I can officially merge the changes in.

2023-02-09 20:49 UTC, HPiyadasa approved these changes

2023-02-09 22:11 UTC, merged