Allow user to set an explicit skip flag for custom regionprops and marker extraction functionality in notebook 1
angelolab/ark-analysis pull request #897
Opened 2023-02-01 08:21 UTC by alex-l-kong

**What is the purpose of this PR?**

Closes #875. Since PyTorch/Tensorflow optimizations to running these extractions will require more changes to the Docker than anticipated, for now we add the functionality to skip these computations.

**How did you implement your changes**

A flag, `skip_extraction`, can be set for `generate_cell_table`, which gets propagated to the internal extractions, allowing them to avoid running these expensive processes if so desired by the user.

**Remaining issues**

We do need to maintain the `'cell_size'`, `'label'`, `'coords'`, and `'centroid'` features from `regionprops`. The first 3 are needed for indexing and `'centroid-0'` and `'centroid-1'` (generated from `'centroid'`) is needed for spatial LDA.

Please comment if there are additional base features we should keep regardless of if `skip_extraction` is set.

2023-02-02 20:33 UTC, alex-l-kong commented
Tested with the `skip_extraction` flag and it runs about 70-80% times faster without. The number of cells to assign is an unavoidable bottleneck, but without signal extraction on the example dataset it takes on our worst FOVs 40s (it's about 2-3x slower without `skip_extraction`).

2023-02-02 20:47 UTC, ngreenwald requested changes
Skipping the extraction step makes sense for testing purposes to see where the bottleneck is, but for in terms of actual user setting, isn't relevant. The only reason to generate the cell table is to have the extracted intensity values. 

The parameter that would be helpful for the user is the option to skip the custom regionprops functions, which are quite slow. 

My understanding is that all the features in `REGIONPROPS_BASE ` don't contribute materially to the runtime. Is that correct? If so, then having a `skip` flag which sets `REGIONPROPS_SINGLE_COMP ` and `REGIONPROPS_MULTI_COMP` to None would be sufficient. If it's the case that certain features in `REGIONPROPS_BASE` are also slow to compute, then the `skip` flag should also remove any of those slow ones.

2023-02-03 20:22 UTC, alex-l-kong commented
@ngreenwald fixed up the pipeline to only remove `regionprops_single_comp` and `regionprops_multi_comp` and leave marker extraction intact.

By removing certain regionprops base calculations (all but `label`, `centroid`, and `coord`), we can trim the single compartment props retrieval time by several orders (up to 10x for our more expensive FOVs). So I'd say the `skip` step should also set `regionprops_base` to just these features in addition to setting `regionprops_single_comp` and `regionprops_multi_comp` to `[]`.

2023-02-03 20:31 UTC, ngreenwald commented
Got it. And what if you remove centroid and coord as coord as well?

2023-02-03 20:54 UTC, alex-l-kong commented
> Got it. And what if you remove centroid and coord as coord as well?

No significant difference, a few tenths of a second difference at most.

2023-02-03 21:03 UTC, ngreenwald commented
great, sounds good

2023-02-03 22:28 UTC, ngreenwald requested changes
The documentation needs to be updated to reflect the behavior of skip extraction. Will you also add a flag in notebook1 with a description where the user can toggle this on or off?

2023-02-03 22:28 UTC, ngreenwald commented on ark/segmentation/marker_quantification.py
> +            if set, skips both the regionprops and the signal extraction steps regardless of
This isn't true anymore. We should change the documentation, and also the name of the flag, to reflect the behavior. Maybe `fast_extraction`

2023-02-05 17:02 UTC, ngreenwald approved these changes
Looks good!

2023-02-05 17:03 UTC, merged