Ark Refactor
angelolab/ark-analysis pull request #935
Opened 2023-02-21 23:20 UTC by srivarra

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Addresses part of #901.

**How did you implement your changes**

Moved `utils.synthetic_spatial_datagen` to `tests/`.
Moved `utils.spatial_analysis_utils` to `src/ark/analysis/`

Added a disk utility to see the space of the runner.

**Remaining issues**

N/A

2023-02-22 23:13 UTC, ngreenwald requested changes
Just some minor syntax

2023-02-22 23:13 UTC, ngreenwald commented on tests/utils/notebooks_test.py
> +from email.mime import base
What's this for?

2023-02-22 23:13 UTC, ngreenwald commented on tests/utils/deepcell_service_utils_test.py
> +# import test_utils
stray import

2023-02-22 23:15 UTC, srivarra commented on tests/utils/notebooks_test.py
> +from email.mime import base
No idea.

2023-02-23 01:12 UTC, ngreenwald approved these changes
Looks good! Testing out the merge queue again

2023-02-23 01:26 UTC, merged