GitHub Actions, Python 3.9+ Support, Jupyterlab Extensions
angelolab/ark-analysis pull request #991
Opened 2023-05-11 23:35 UTC by srivarra

**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

- Closes #965.
- Closes #899.

Adds a Conda environment using Python 3.11.
The docker environment now runs Python 3.11.

**How did you implement your changes**

Added the `environment.yml` file, adjusted the `Dockerfile`, made changes to the `README` and reformatted the `setup.py` file. 

**Remaining issues**

N/A.

2023-05-17 21:07 UTC, alex-l-kong approved these changes
Looks good

2023-05-17 21:59 UTC, ngreenwald requested changes
We should get the sequencing right for all of this. If @cliu72  wants the updated version for her paper to to be 3.9+, then we should wait on merging in #985 until after this. 

If not, then we should make a new release once her other requests get merged in, then #985, then this.

2023-05-18 21:29 UTC, cliu72 commented
> We should get the sequencing right for all of this. If @cliu72 wants the updated version for her paper to to be 3.9+, then we should wait on merging in #985 until after this.
> 
> If not, then we should make a new release once her other requests get merged in, then #985, then this.

Yeah I think it'd be good for the updated version of my paper to be 3.9+, since pip install doesn't work anymore.

2023-06-05 21:08 UTC, camisowers requested changes
Minor comment about the alpineer version, but other than that it looks great.

2023-06-05 21:08 UTC, camisowers commented on environment.yml
> +    - alpineer==0.1.7
Should we bump alpineer to 0.1.8 instead? [https://github.com/angelolab/alpineer/releases/tag/v0.1.8](https://github.com/angelolab/alpineer/releases/tag/v0.1.8)

2023-06-07 21:20 UTC, srivarra commented
@ngreenwald This is good to go. 

@camisowers @alex-l-kong   Added the fix in for `watershed`'s argument `dtype`.

2023-06-07 23:21 UTC, ngreenwald approved these changes
Looks great! Big upgrades

2023-06-08 17:27 UTC, camisowers approved these changes

2023-06-08 17:27 UTC, camisowers approved these changes

2023-06-09 22:37 UTC, merged